name: spaceship-titanic-dev
channels:
  - conda-forge
dependencies:
  - python=3.8.13
  - pip=22.0.2
  - jupyterlab=3.4.8
  - black-jupyter=22.10.0
  - pandas=1.5.0
  - scikit-learn=1.1.2
  # https://github.com/scikit-learn-contrib/category_encoders
  - category_encoders=2.5.0
